apiVersion: v1
kind: Service
metadata:
  name: {{ include "parallax.fullname" . }}
  labels:
    app: {{ include "parallax.name" . }}
    chart: {{ include "parallax.chart" . }}
    release: {{ .Release.Name }}
    component: ingress
  {{- if .Values.internal }}
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  {{- end }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: {{ .Values.rpcPort }}
    name: rpc
  selector:
    app: {{ include "parallax.name" . }}
    release: {{ .Release.Name }}
    component: worker
